name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installation des dépendances
        run: pip install -r requirements-dev.txt

      - name: Exécution des tests
        run: pytest -v
